/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ad_ffmpeg_VideoAndAudioPlayer */

#ifndef _Included_com_ad_ffmpeg_VideoAndAudioPlayer
#define _Included_com_ad_ffmpeg_VideoAndAudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ad_ffmpeg_VideoAndAudioPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ad_ffmpeg_VideoAndAudioPlayer_render
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ad_ffmpeg_VideoAndAudioPlayer
 * Method:    sound
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ad_ffmpeg_VideoAndAudioPlayer_sound
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ad_ffmpeg_VideoAndAudioPlayer
 * Method:    play
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ad_ffmpeg_VideoAndAudioPlayer_play
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
